trigger:
- main

pool:
  name: selfhostedpool
  # Replace with your self-hosted agent pool name
  # Remove vmImage since we're using self-hosted agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

